#!/bin/bash

sudo apt-get update
sudo apt-get install -y git curl
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs
git clone https://github.com/dpetrouk/tornado-electron-test.git
cd tornado-electron-test
npm install
npm start